services:
  - type: web
    name: your-app-name
    env: node
    plan: free # or the plan you prefer (free, starter, etc.)
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        value: "your-mongodb-connection-string" # Ensure to replace with your MongoDB Atlas URI
      - key: NODE_ENV
        value: production
